package com.guochen.model;

public class TBuyer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyer.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyer.buyer_name
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String buyerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyer.buyer_addr
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String buyerAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyer.buyer_phone
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String buyerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyer.buyer_bank_account
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String buyerBankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyer.buyer_account
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String buyerAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyer.buyer_taxrece_no
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String buyerTaxreceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyer.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyer.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyer.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_buyer.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyer.id
     *
     * @return the value of t_buyer.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyer.id
     *
     * @param id the value for t_buyer.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyer.buyer_name
     *
     * @return the value of t_buyer.buyer_name
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyer.buyer_name
     *
     * @param buyerName the value for t_buyer.buyer_name
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName == null ? null : buyerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyer.buyer_addr
     *
     * @return the value of t_buyer.buyer_addr
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getBuyerAddr() {
        return buyerAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyer.buyer_addr
     *
     * @param buyerAddr the value for t_buyer.buyer_addr
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setBuyerAddr(String buyerAddr) {
        this.buyerAddr = buyerAddr == null ? null : buyerAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyer.buyer_phone
     *
     * @return the value of t_buyer.buyer_phone
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getBuyerPhone() {
        return buyerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyer.buyer_phone
     *
     * @param buyerPhone the value for t_buyer.buyer_phone
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setBuyerPhone(String buyerPhone) {
        this.buyerPhone = buyerPhone == null ? null : buyerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyer.buyer_bank_account
     *
     * @return the value of t_buyer.buyer_bank_account
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getBuyerBankAccount() {
        return buyerBankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyer.buyer_bank_account
     *
     * @param buyerBankAccount the value for t_buyer.buyer_bank_account
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setBuyerBankAccount(String buyerBankAccount) {
        this.buyerBankAccount = buyerBankAccount == null ? null : buyerBankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyer.buyer_account
     *
     * @return the value of t_buyer.buyer_account
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getBuyerAccount() {
        return buyerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyer.buyer_account
     *
     * @param buyerAccount the value for t_buyer.buyer_account
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setBuyerAccount(String buyerAccount) {
        this.buyerAccount = buyerAccount == null ? null : buyerAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyer.buyer_taxrece_no
     *
     * @return the value of t_buyer.buyer_taxrece_no
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getBuyerTaxreceNo() {
        return buyerTaxreceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyer.buyer_taxrece_no
     *
     * @param buyerTaxreceNo the value for t_buyer.buyer_taxrece_no
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setBuyerTaxreceNo(String buyerTaxreceNo) {
        this.buyerTaxreceNo = buyerTaxreceNo == null ? null : buyerTaxreceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyer.create_time
     *
     * @return the value of t_buyer.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyer.create_time
     *
     * @param createTime the value for t_buyer.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyer.update_time
     *
     * @return the value of t_buyer.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyer.update_time
     *
     * @param updateTime the value for t_buyer.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyer.alternate_field1
     *
     * @return the value of t_buyer.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField1() {
        return alternateField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyer.alternate_field1
     *
     * @param alternateField1 the value for t_buyer.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField1(String alternateField1) {
        this.alternateField1 = alternateField1 == null ? null : alternateField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_buyer.alternate_field2
     *
     * @return the value of t_buyer.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField2() {
        return alternateField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_buyer.alternate_field2
     *
     * @param alternateField2 the value for t_buyer.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField2(String alternateField2) {
        this.alternateField2 = alternateField2 == null ? null : alternateField2.trim();
    }
}