package com.guochen.model;

public class TCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.id
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.code_type
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    private String codeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.code_name
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    private String codeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.code_value
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    private String codeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.create_time
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.update_time
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.alternate_field1
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    private String alternateField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code.alternate_field2
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    private String alternateField2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.id
     *
     * @return the value of t_code.id
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.id
     *
     * @param id the value for t_code.id
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.code_type
     *
     * @return the value of t_code.code_type
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.code_type
     *
     * @param codeType the value for t_code.code_type
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.code_name
     *
     * @return the value of t_code.code_name
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public String getCodeName() {
        return codeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.code_name
     *
     * @param codeName the value for t_code.code_name
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public void setCodeName(String codeName) {
        this.codeName = codeName == null ? null : codeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.code_value
     *
     * @return the value of t_code.code_value
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public String getCodeValue() {
        return codeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.code_value
     *
     * @param codeValue the value for t_code.code_value
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue == null ? null : codeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.create_time
     *
     * @return the value of t_code.create_time
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.create_time
     *
     * @param createTime the value for t_code.create_time
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.update_time
     *
     * @return the value of t_code.update_time
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.update_time
     *
     * @param updateTime the value for t_code.update_time
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.alternate_field1
     *
     * @return the value of t_code.alternate_field1
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public String getAlternateField1() {
        return alternateField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.alternate_field1
     *
     * @param alternateField1 the value for t_code.alternate_field1
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public void setAlternateField1(String alternateField1) {
        this.alternateField1 = alternateField1 == null ? null : alternateField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code.alternate_field2
     *
     * @return the value of t_code.alternate_field2
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public String getAlternateField2() {
        return alternateField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code.alternate_field2
     *
     * @param alternateField2 the value for t_code.alternate_field2
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    public void setAlternateField2(String alternateField2) {
        this.alternateField2 = alternateField2 == null ? null : alternateField2.trim();
    }
}