package com.guochen.model;

public class TCom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.id
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.com_name
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String comName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.con_name
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String conName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.con_phone
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String conPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.bu_scope_id
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String buScopeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.com_type
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String comType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.business_license_path
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String businessLicensePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.taxrece_path
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String taxrecePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.orcode_path
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String orcodePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.ceau_path
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String ceauPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.bank_account
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String bankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.taxrece_no
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String taxreceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.account
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.com_addr
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String comAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.com_phone
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String comPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.break_no
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private Integer breakNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.create_time
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.update_time
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.alternate_field1
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String alternateField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_com.alternate_field2
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    private String alternateField2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.id
     *
     * @return the value of t_com.id
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.id
     *
     * @param id the value for t_com.id
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.com_name
     *
     * @return the value of t_com.com_name
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getComName() {
        return comName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.com_name
     *
     * @param comName the value for t_com.com_name
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setComName(String comName) {
        this.comName = comName == null ? null : comName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.con_name
     *
     * @return the value of t_com.con_name
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getConName() {
        return conName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.con_name
     *
     * @param conName the value for t_com.con_name
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setConName(String conName) {
        this.conName = conName == null ? null : conName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.con_phone
     *
     * @return the value of t_com.con_phone
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getConPhone() {
        return conPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.con_phone
     *
     * @param conPhone the value for t_com.con_phone
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setConPhone(String conPhone) {
        this.conPhone = conPhone == null ? null : conPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.bu_scope_id
     *
     * @return the value of t_com.bu_scope_id
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getBuScopeId() {
        return buScopeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.bu_scope_id
     *
     * @param buScopeId the value for t_com.bu_scope_id
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setBuScopeId(String buScopeId) {
        this.buScopeId = buScopeId == null ? null : buScopeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.com_type
     *
     * @return the value of t_com.com_type
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getComType() {
        return comType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.com_type
     *
     * @param comType the value for t_com.com_type
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setComType(String comType) {
        this.comType = comType == null ? null : comType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.business_license_path
     *
     * @return the value of t_com.business_license_path
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getBusinessLicensePath() {
        return businessLicensePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.business_license_path
     *
     * @param businessLicensePath the value for t_com.business_license_path
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setBusinessLicensePath(String businessLicensePath) {
        this.businessLicensePath = businessLicensePath == null ? null : businessLicensePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.taxrece_path
     *
     * @return the value of t_com.taxrece_path
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getTaxrecePath() {
        return taxrecePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.taxrece_path
     *
     * @param taxrecePath the value for t_com.taxrece_path
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setTaxrecePath(String taxrecePath) {
        this.taxrecePath = taxrecePath == null ? null : taxrecePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.orcode_path
     *
     * @return the value of t_com.orcode_path
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getOrcodePath() {
        return orcodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.orcode_path
     *
     * @param orcodePath the value for t_com.orcode_path
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setOrcodePath(String orcodePath) {
        this.orcodePath = orcodePath == null ? null : orcodePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.ceau_path
     *
     * @return the value of t_com.ceau_path
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getCeauPath() {
        return ceauPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.ceau_path
     *
     * @param ceauPath the value for t_com.ceau_path
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setCeauPath(String ceauPath) {
        this.ceauPath = ceauPath == null ? null : ceauPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.bank_account
     *
     * @return the value of t_com.bank_account
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.bank_account
     *
     * @param bankAccount the value for t_com.bank_account
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.taxrece_no
     *
     * @return the value of t_com.taxrece_no
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getTaxreceNo() {
        return taxreceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.taxrece_no
     *
     * @param taxreceNo the value for t_com.taxrece_no
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setTaxreceNo(String taxreceNo) {
        this.taxreceNo = taxreceNo == null ? null : taxreceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.account
     *
     * @return the value of t_com.account
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.account
     *
     * @param account the value for t_com.account
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.com_addr
     *
     * @return the value of t_com.com_addr
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getComAddr() {
        return comAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.com_addr
     *
     * @param comAddr the value for t_com.com_addr
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setComAddr(String comAddr) {
        this.comAddr = comAddr == null ? null : comAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.com_phone
     *
     * @return the value of t_com.com_phone
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getComPhone() {
        return comPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.com_phone
     *
     * @param comPhone the value for t_com.com_phone
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setComPhone(String comPhone) {
        this.comPhone = comPhone == null ? null : comPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.break_no
     *
     * @return the value of t_com.break_no
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public Integer getBreakNo() {
        return breakNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.break_no
     *
     * @param breakNo the value for t_com.break_no
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setBreakNo(Integer breakNo) {
        this.breakNo = breakNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.create_time
     *
     * @return the value of t_com.create_time
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.create_time
     *
     * @param createTime the value for t_com.create_time
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.update_time
     *
     * @return the value of t_com.update_time
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.update_time
     *
     * @param updateTime the value for t_com.update_time
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.alternate_field1
     *
     * @return the value of t_com.alternate_field1
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getAlternateField1() {
        return alternateField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.alternate_field1
     *
     * @param alternateField1 the value for t_com.alternate_field1
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setAlternateField1(String alternateField1) {
        this.alternateField1 = alternateField1 == null ? null : alternateField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_com.alternate_field2
     *
     * @return the value of t_com.alternate_field2
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public String getAlternateField2() {
        return alternateField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_com.alternate_field2
     *
     * @param alternateField2 the value for t_com.alternate_field2
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    public void setAlternateField2(String alternateField2) {
        this.alternateField2 = alternateField2 == null ? null : alternateField2.trim();
    }

    private String unpassReason;

    private String userStatus;
    private String forbidUser;
    private String forbidTime;
    private String forbidReason;
    private String files;
	private TUser user;
    
	
	public TUser getUser() {
		return user;
	}

	public void setUser(TUser user) {
		this.user = user;
	}

	public String getFiles() {
		return files;
	}

	public void setFiles(String files) {
		this.files = files;
	}

	public String getUserStatus() {
		return userStatus;
	}
	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}
	public String getForbidUser() {
		return forbidUser;
	}
	public void setForbidUser(String forbidUser) {
		this.forbidUser = forbidUser;
	}
	public String getForbidTime() {
		return forbidTime;
	}
	public void setForbidTime(String forbidTime) {
		this.forbidTime = forbidTime;
	}
	public String getForbidReason() {
		return forbidReason;
	}
	public void setForbidReason(String forbidReason) {
		this.forbidReason = forbidReason;
	}

	public String getUnpassReason() {
		return unpassReason;
	}

	public void setUnpassReason(String unpassReason) {
		this.unpassReason = unpassReason;
	}
	
}