package com.guochen.model;

public class TConapp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conapp.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conapp.contract_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conapp.node_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conapp.app_status
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String appStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conapp.take_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String takeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conapp.app_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String appTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conapp.app_ex
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String appEx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conapp.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conapp.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conapp.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_conapp.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conapp.id
     *
     * @return the value of t_conapp.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conapp.id
     *
     * @param id the value for t_conapp.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conapp.contract_id
     *
     * @return the value of t_conapp.contract_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conapp.contract_id
     *
     * @param contractId the value for t_conapp.contract_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conapp.node_id
     *
     * @return the value of t_conapp.node_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conapp.node_id
     *
     * @param nodeId the value for t_conapp.node_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conapp.app_status
     *
     * @return the value of t_conapp.app_status
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conapp.app_status
     *
     * @param appStatus the value for t_conapp.app_status
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus == null ? null : appStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conapp.take_time
     *
     * @return the value of t_conapp.take_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getTakeTime() {
        return takeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conapp.take_time
     *
     * @param takeTime the value for t_conapp.take_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setTakeTime(String takeTime) {
        this.takeTime = takeTime == null ? null : takeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conapp.app_time
     *
     * @return the value of t_conapp.app_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAppTime() {
        return appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conapp.app_time
     *
     * @param appTime the value for t_conapp.app_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAppTime(String appTime) {
        this.appTime = appTime == null ? null : appTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conapp.app_ex
     *
     * @return the value of t_conapp.app_ex
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAppEx() {
        return appEx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conapp.app_ex
     *
     * @param appEx the value for t_conapp.app_ex
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAppEx(String appEx) {
        this.appEx = appEx == null ? null : appEx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conapp.create_time
     *
     * @return the value of t_conapp.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conapp.create_time
     *
     * @param createTime the value for t_conapp.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conapp.update_time
     *
     * @return the value of t_conapp.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conapp.update_time
     *
     * @param updateTime the value for t_conapp.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conapp.alternate_field1
     *
     * @return the value of t_conapp.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField1() {
        return alternateField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conapp.alternate_field1
     *
     * @param alternateField1 the value for t_conapp.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField1(String alternateField1) {
        this.alternateField1 = alternateField1 == null ? null : alternateField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_conapp.alternate_field2
     *
     * @return the value of t_conapp.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField2() {
        return alternateField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_conapp.alternate_field2
     *
     * @param alternateField2 the value for t_conapp.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField2(String alternateField2) {
        this.alternateField2 = alternateField2 == null ? null : alternateField2.trim();
    }
    
    private TNode node;
    private TContract contract;
	public TNode getNode() {
		return node;
	}
	public void setNode(TNode node) {
		this.node = node;
	}
	public TContract getContract() {
		return contract;
	}
	public void setContract(TContract contract) {
		this.contract = contract;
	}
    
}