package com.guochen.model;

public class TContract {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.pro_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.user_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.con
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String con;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.delivery_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String deliveryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.se_me
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String seMe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.template_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.file_path
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.app_status
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String appStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField2;
    private String jc;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.id
     *
     * @return the value of t_contract.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.id
     *
     * @param id the value for t_contract.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.pro_id
     *
     * @return the value of t_contract.pro_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.pro_id
     *
     * @param proId the value for t_contract.pro_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.user_id
     *
     * @return the value of t_contract.user_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.user_id
     *
     * @param userId the value for t_contract.user_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.con
     *
     * @return the value of t_contract.con
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getCon() {
        return con;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.con
     *
     * @param con the value for t_contract.con
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setCon(String con) {
        this.con = con == null ? null : con.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.delivery_time
     *
     * @return the value of t_contract.delivery_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.delivery_time
     *
     * @param deliveryTime the value for t_contract.delivery_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setDeliveryTime(String deliveryTime) {
        this.deliveryTime = deliveryTime == null ? null : deliveryTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.se_me
     *
     * @return the value of t_contract.se_me
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getSeMe() {
        return seMe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.se_me
     *
     * @param seMe the value for t_contract.se_me
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setSeMe(String seMe) {
        this.seMe = seMe == null ? null : seMe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.template_id
     *
     * @return the value of t_contract.template_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.template_id
     *
     * @param templateId the value for t_contract.template_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.file_path
     *
     * @return the value of t_contract.file_path
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.file_path
     *
     * @param filePath the value for t_contract.file_path
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.app_status
     *
     * @return the value of t_contract.app_status
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.app_status
     *
     * @param appStatus the value for t_contract.app_status
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus == null ? null : appStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.create_time
     *
     * @return the value of t_contract.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.create_time
     *
     * @param createTime the value for t_contract.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.update_time
     *
     * @return the value of t_contract.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.update_time
     *
     * @param updateTime the value for t_contract.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.alternate_field1
     *
     * @return the value of t_contract.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField1() {
        return alternateField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.alternate_field1
     *
     * @param alternateField1 the value for t_contract.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField1(String alternateField1) {
        this.alternateField1 = alternateField1 == null ? null : alternateField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract.alternate_field2
     *
     * @return the value of t_contract.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField2() {
        return alternateField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract.alternate_field2
     *
     * @param alternateField2 the value for t_contract.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField2(String alternateField2) {
        this.alternateField2 = alternateField2 == null ? null : alternateField2.trim();
    }
    
    private TOffer offer;
    private TProject project;
    private TUser user;
    private int offerId;
    private String proName;
    private String proStatus;
    private String projectNo;
	public TUser getUser() {
		return user;
	}

	public void setUser(TUser user) {
		this.user = user;
	}

	public TProject getProject() {
		return project;
	}

	public void setProject(TProject project) {
		this.project = project;
	}

	public TOffer getOffer() {
		return offer;
	}
	public void setOffer(TOffer offer) {
		this.offer = offer;
	}

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public String getProStatus() {
		return proStatus;
	}

	public void setProStatus(String proStatus) {
		this.proStatus = proStatus;
	}

	public int getOfferId() {
		return offerId;
	}

	public void setOfferId(int offerId) {
		this.offerId = offerId;
	}

	public String getJc() {
		return jc;
	}

	public void setJc(String jc) {
		this.jc = jc;
	}

	public String getProjectNo() {
		return projectNo;
	}

	public void setProjectNo(String projectNo) {
		this.projectNo = projectNo;
	}

}