package com.guochen.model;

import java.util.List;

public class TNode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.front_node_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer frontNodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.rear_node_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer rearNodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.node_name
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String nodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.user_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_node.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.id
     *
     * @return the value of t_node.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.id
     *
     * @param id the value for t_node.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.front_node_id
     *
     * @return the value of t_node.front_node_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getFrontNodeId() {
        return frontNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.front_node_id
     *
     * @param frontNodeId the value for t_node.front_node_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setFrontNodeId(Integer frontNodeId) {
        this.frontNodeId = frontNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.rear_node_id
     *
     * @return the value of t_node.rear_node_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getRearNodeId() {
        return rearNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.rear_node_id
     *
     * @param rearNodeId the value for t_node.rear_node_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setRearNodeId(Integer rearNodeId) {
        this.rearNodeId = rearNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.node_name
     *
     * @return the value of t_node.node_name
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.node_name
     *
     * @param nodeName the value for t_node.node_name
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.user_id
     *
     * @return the value of t_node.user_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.user_id
     *
     * @param userId the value for t_node.user_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.create_time
     *
     * @return the value of t_node.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.create_time
     *
     * @param createTime the value for t_node.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.update_time
     *
     * @return the value of t_node.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.update_time
     *
     * @param updateTime the value for t_node.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.alternate_field1
     *
     * @return the value of t_node.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField1() {
        return alternateField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.alternate_field1
     *
     * @param alternateField1 the value for t_node.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField1(String alternateField1) {
        this.alternateField1 = alternateField1 == null ? null : alternateField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_node.alternate_field2
     *
     * @return the value of t_node.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField2() {
        return alternateField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_node.alternate_field2
     *
     * @param alternateField2 the value for t_node.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField2(String alternateField2) {
        this.alternateField2 = alternateField2 == null ? null : alternateField2.trim();
    }
    
    private TUser user;

	public TUser getUser() {
		return user;
	}

	public void setUser(TUser user) {
		this.user = user;
	}
    
}