package com.guochen.model;

public class TNotice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.notice_title
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String noticeTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.notice_con
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String noticeCon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.notice_type
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String noticeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.notice_status
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String noticeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.id
     *
     * @return the value of t_notice.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.id
     *
     * @param id the value for t_notice.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.notice_title
     *
     * @return the value of t_notice.notice_title
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getNoticeTitle() {
        return noticeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.notice_title
     *
     * @param noticeTitle the value for t_notice.notice_title
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setNoticeTitle(String noticeTitle) {
        this.noticeTitle = noticeTitle == null ? null : noticeTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.notice_con
     *
     * @return the value of t_notice.notice_con
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getNoticeCon() {
        return noticeCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.notice_con
     *
     * @param noticeCon the value for t_notice.notice_con
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setNoticeCon(String noticeCon) {
        this.noticeCon = noticeCon == null ? null : noticeCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.notice_type
     *
     * @return the value of t_notice.notice_type
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getNoticeType() {
        return noticeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.notice_type
     *
     * @param noticeType the value for t_notice.notice_type
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setNoticeType(String noticeType) {
        this.noticeType = noticeType == null ? null : noticeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.notice_status
     *
     * @return the value of t_notice.notice_status
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getNoticeStatus() {
        return noticeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.notice_status
     *
     * @param noticeStatus the value for t_notice.notice_status
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setNoticeStatus(String noticeStatus) {
        this.noticeStatus = noticeStatus == null ? null : noticeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.create_time
     *
     * @return the value of t_notice.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.create_time
     *
     * @param createTime the value for t_notice.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.update_time
     *
     * @return the value of t_notice.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.update_time
     *
     * @param updateTime the value for t_notice.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.alternate_field1
     *
     * @return the value of t_notice.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField1() {
        return alternateField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.alternate_field1
     *
     * @param alternateField1 the value for t_notice.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField1(String alternateField1) {
        this.alternateField1 = alternateField1 == null ? null : alternateField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.alternate_field2
     *
     * @return the value of t_notice.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField2() {
        return alternateField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.alternate_field2
     *
     * @param alternateField2 the value for t_notice.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField2(String alternateField2) {
        this.alternateField2 = alternateField2 == null ? null : alternateField2.trim();
    }
}