package com.guochen.model;

import com.guochen.utils.CommonUtils;

public class TOffer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer.pro_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer.user_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer.offer_sheet_path
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String offerSheetPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer.acce_offer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String acceOffer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer.cash_offer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String cashOffer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer.fre_offer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String freOffer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer.remarks
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_offer.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer.id
     *
     * @return the value of t_offer.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer.id
     *
     * @param id the value for t_offer.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer.pro_id
     *
     * @return the value of t_offer.pro_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer.pro_id
     *
     * @param proId the value for t_offer.pro_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer.user_id
     *
     * @return the value of t_offer.user_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer.user_id
     *
     * @param userId the value for t_offer.user_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer.offer_sheet_path
     *
     * @return the value of t_offer.offer_sheet_path
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getOfferSheetPath() {
        return offerSheetPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer.offer_sheet_path
     *
     * @param offerSheetPath the value for t_offer.offer_sheet_path
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setOfferSheetPath(String offerSheetPath) {
        this.offerSheetPath = offerSheetPath == null ? null : offerSheetPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer.acce_offer
     *
     * @return the value of t_offer.acce_offer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAcceOffer() {
        return acceOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer.acce_offer
     *
     * @param acceOffer the value for t_offer.acce_offer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAcceOffer(String acceOffer) {
        this.acceOffer = acceOffer == null ? null : acceOffer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer.cash_offer
     *
     * @return the value of t_offer.cash_offer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getCashOffer() {
        return cashOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer.cash_offer
     *
     * @param cashOffer the value for t_offer.cash_offer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setCashOffer(String cashOffer) {
        this.cashOffer = cashOffer == null ? null : cashOffer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer.fre_offer
     *
     * @return the value of t_offer.fre_offer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getFreOffer() {
        return freOffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer.fre_offer
     *
     * @param freOffer the value for t_offer.fre_offer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setFreOffer(String freOffer) {
        this.freOffer = freOffer == null ? null : freOffer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer.remarks
     *
     * @return the value of t_offer.remarks
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer.remarks
     *
     * @param remarks the value for t_offer.remarks
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer.create_time
     *
     * @return the value of t_offer.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer.create_time
     *
     * @param createTime the value for t_offer.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer.update_time
     *
     * @return the value of t_offer.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer.update_time
     *
     * @param updateTime the value for t_offer.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer.alternate_field1
     *
     * @return the value of t_offer.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField1() {
        return alternateField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer.alternate_field1
     *
     * @param alternateField1 the value for t_offer.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField1(String alternateField1) {
        this.alternateField1 = alternateField1 == null ? null : alternateField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_offer.alternate_field2
     *
     * @return the value of t_offer.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField2() {
        return alternateField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_offer.alternate_field2
     *
     * @param alternateField2 the value for t_offer.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField2(String alternateField2) {
        this.alternateField2 = alternateField2 == null ? null : alternateField2.trim();
    }
    
    private String status;//
    
    
    private TProject project;
    private TCom com;
    private String proName;
    private String proStatus;
    
    private String acceOfferUnion;
    private String freOfferUnion;
    private String cashOfferUnion;
    

	public TProject getProject() {
		return project;
	}

	public void setProject(TProject project) {
		this.project = project;
	}

	public String getProName() {
		return proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public String getProStatus() {
		return proStatus;
	}

	public void setProStatus(String proStatus) {
		this.proStatus = proStatus;
	}

	public TCom getCom() {
		return com;
	}

	public void setCom(TCom com) {
		this.com = com;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getAcceOfferUnion() {
		return acceOfferUnion;
	}

	public void setAcceOfferUnion(String acceOfferUnion) {
		this.acceOfferUnion = acceOfferUnion;
	}

	public String getFreOfferUnion() {
		return freOfferUnion;
	}

	public void setFreOfferUnion(String freOfferUnion) {
		this.freOfferUnion = freOfferUnion;
	}

	public String getCashOfferUnion() {
		return cashOfferUnion;
	}

	public void setCashOfferUnion(String cashOfferUnion) {
		this.cashOfferUnion = cashOfferUnion;
	}
	private double doubleOfAcceOffer;
	private double doubleOfCashOffer;
	private double doubleOfFreOffer;

	public double getDoubleOfAcceOffer() {
		if(acceOffer!=null && !"".endsWith(acceOffer)){
			return CommonUtils.str2Double(acceOffer);
		}
		return doubleOfAcceOffer;
	}

	public void setDoubleOfAcceOffer(double doubleOfAcceOffer) {
		this.doubleOfAcceOffer = doubleOfAcceOffer;
	}

	public double getDoubleOfCashOffer() {
		if(cashOffer!=null && !"".endsWith(cashOffer)){
			return CommonUtils.str2Double(cashOffer);
		}
		return doubleOfCashOffer;
	}

	public void setDoubleOfCashOffer(double doubleOfCashOffer) {
		this.doubleOfCashOffer = doubleOfCashOffer;
	}

	public double getDoubleOfFreOffer() {
		if(freOffer!=null && !"".endsWith(freOffer)){
			return CommonUtils.str2Double(freOffer);
		}
		return doubleOfFreOffer;
	}

	public void setDoubleOfFreOffer(double doubleOfFreOffer) {
		this.doubleOfFreOffer = doubleOfFreOffer;
	}
	
}