package com.guochen.model;

public class TQuickMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quick_msg.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quick_msg.remind_con
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String remindCon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quick_msg.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quick_msg.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quick_msg.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quick_msg.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quick_msg.id
     *
     * @return the value of t_quick_msg.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quick_msg.id
     *
     * @param id the value for t_quick_msg.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quick_msg.remind_con
     *
     * @return the value of t_quick_msg.remind_con
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getRemindCon() {
        return remindCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quick_msg.remind_con
     *
     * @param remindCon the value for t_quick_msg.remind_con
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setRemindCon(String remindCon) {
        this.remindCon = remindCon == null ? null : remindCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quick_msg.create_time
     *
     * @return the value of t_quick_msg.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quick_msg.create_time
     *
     * @param createTime the value for t_quick_msg.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quick_msg.update_time
     *
     * @return the value of t_quick_msg.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quick_msg.update_time
     *
     * @param updateTime the value for t_quick_msg.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quick_msg.alternate_field1
     *
     * @return the value of t_quick_msg.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField1() {
        return alternateField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quick_msg.alternate_field1
     *
     * @param alternateField1 the value for t_quick_msg.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField1(String alternateField1) {
        this.alternateField1 = alternateField1 == null ? null : alternateField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quick_msg.alternate_field2
     *
     * @return the value of t_quick_msg.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField2() {
        return alternateField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quick_msg.alternate_field2
     *
     * @param alternateField2 the value for t_quick_msg.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField2(String alternateField2) {
        this.alternateField2 = alternateField2 == null ? null : alternateField2.trim();
    }
}