package com.guochen.model;

public class TRoleAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_authority.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_authority.authority_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer authorityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_authority.role_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_authority.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_authority.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_authority.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_authority.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_authority.id
     *
     * @return the value of t_role_authority.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_authority.id
     *
     * @param id the value for t_role_authority.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_authority.authority_id
     *
     * @return the value of t_role_authority.authority_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_authority.authority_id
     *
     * @param authorityId the value for t_role_authority.authority_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_authority.role_id
     *
     * @return the value of t_role_authority.role_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_authority.role_id
     *
     * @param roleId the value for t_role_authority.role_id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_authority.create_time
     *
     * @return the value of t_role_authority.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_authority.create_time
     *
     * @param createTime the value for t_role_authority.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_authority.update_time
     *
     * @return the value of t_role_authority.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_authority.update_time
     *
     * @param updateTime the value for t_role_authority.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_authority.alternate_field1
     *
     * @return the value of t_role_authority.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField1() {
        return alternateField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_authority.alternate_field1
     *
     * @param alternateField1 the value for t_role_authority.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField1(String alternateField1) {
        this.alternateField1 = alternateField1 == null ? null : alternateField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_authority.alternate_field2
     *
     * @return the value of t_role_authority.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField2() {
        return alternateField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_authority.alternate_field2
     *
     * @param alternateField2 the value for t_role_authority.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField2(String alternateField2) {
        this.alternateField2 = alternateField2 == null ? null : alternateField2.trim();
    }
}