package com.guochen.model;

public class TTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.template_name
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.template_path
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String templatePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    private String alternateField2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.id
     *
     * @return the value of t_template.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.id
     *
     * @param id the value for t_template.id
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.template_name
     *
     * @return the value of t_template.template_name
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.template_name
     *
     * @param templateName the value for t_template.template_name
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.template_path
     *
     * @return the value of t_template.template_path
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getTemplatePath() {
        return templatePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.template_path
     *
     * @param templatePath the value for t_template.template_path
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setTemplatePath(String templatePath) {
        this.templatePath = templatePath == null ? null : templatePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.create_time
     *
     * @return the value of t_template.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.create_time
     *
     * @param createTime the value for t_template.create_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.update_time
     *
     * @return the value of t_template.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.update_time
     *
     * @param updateTime the value for t_template.update_time
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.alternate_field1
     *
     * @return the value of t_template.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField1() {
        return alternateField1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.alternate_field1
     *
     * @param alternateField1 the value for t_template.alternate_field1
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField1(String alternateField1) {
        this.alternateField1 = alternateField1 == null ? null : alternateField1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.alternate_field2
     *
     * @return the value of t_template.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public String getAlternateField2() {
        return alternateField2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.alternate_field2
     *
     * @param alternateField2 the value for t_template.alternate_field2
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    public void setAlternateField2(String alternateField2) {
        this.alternateField2 = alternateField2 == null ? null : alternateField2.trim();
    }
    
    private String templateNameQuery;
    private String queryDate1;
    private String queryDate2;

	public String getQueryDate1() {
		return queryDate1;
	}

	public void setQueryDate1(String queryDate1) {
		this.queryDate1 = queryDate1;
	}

	public String getQueryDate2() {
		return queryDate2;
	}

	public void setQueryDate2(String queryDate2) {
		this.queryDate2 = queryDate2;
	}

	public String getTemplateNameQuery() {
		return templateNameQuery;
	}

	public void setTemplateNameQuery(String templateNameQuery) {
		this.templateNameQuery = templateNameQuery;
	}
    
}