package com.guochen.dao;

import com.guochen.model.TBuScope;
import java.util.List;

public interface TBuScopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bu_scope
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bu_scope
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int insert(TBuScope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bu_scope
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    TBuScope selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bu_scope
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    List<TBuScope> selectAll(TBuScope scope);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bu_scope
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int updateByPrimaryKey(TBuScope record);
}