package com.guochen.dao;

import com.guochen.model.TBuyer;
import com.guochen.model.TUser;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

public interface TBuyerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buyer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buyer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int insert(TBuyer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buyer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    TBuyer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buyer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    List<TBuyer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buyer
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int updateByPrimaryKey(TBuyer record);
    
    public List<TBuyer> selectPageList(RowBounds rowBounds, TBuyer record);
    public Long selectPageCount(TBuyer record);
}