package com.guochen.dao;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.guochen.model.TBuyer;
import com.guochen.model.TCode;

public interface TCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    int insert(TCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    TCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    List<TCode> selectAll();
    List<TCode> selectAllByCodeType(String codeType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_code
     *
     * @mbg.generated Tue Dec 27 03:11:59 CST 2016
     */
    int updateByPrimaryKey(TCode record);
    
    public List<TCode> selectPageList(RowBounds rowBounds, TCode record);
    public Long selectPageCount(TCode record);
}