package com.guochen.dao;

import com.guochen.model.TCom;
import com.guochen.model.TProject;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

public interface TComMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_com
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_com
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    int insert(TCom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_com
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    TCom selectByPrimaryKey(Integer id);
    
    TCom selectByUserId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_com
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    List<TCom> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_com
     *
     * @mbg.generated Mon Dec 26 20:05:50 CST 2016
     */
    int updateByPrimaryKey(TCom record);
    
    public List<TCom> selectPageList(RowBounds rowBounds, TCom com);
    public List<TCom> selectList(TCom com);
    
    public Long selectPageCount(TCom com);
    
    public void deleteByIds(String[] ids);
    
}