package com.guochen.dao;

import com.guochen.model.TConapp;
import com.guochen.model.TProject;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

public interface TConappMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_conapp
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);
    int deleteByContractId(Integer contractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_conapp
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int insert(TConapp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_conapp
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    TConapp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_conapp
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    List<TConapp> selectAll(int contractId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_conapp
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int updateByPrimaryKey(TConapp record);
    
    TConapp selectCurrentByContractId(int contractId);
    
    public List<TProject> selectAccProjectPageList(RowBounds rowBounds, Integer comId);
    
    public Long selectPageCount(TProject project);
    
    public List<TConapp> mselectVerifyPageList(RowBounds rowBounds, int userId);
    public Long mselectVerifyPageListCount(int userId);
    
    public List<TConapp> selectVerifyPageList(RowBounds rowBounds, TProject project);
    public Long selectVerifyPageListCount(TProject project);
    
}