package com.guochen.dao;

import com.guochen.model.TContract;
import com.guochen.model.TProject;
import com.guochen.page.Page;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.session.RowBounds;

public interface TContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int insert(TContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    TContract selectByPrimaryKey(Integer id);
    TContract selectByProjectId(Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    List<TContract> selectAll(TContract contract);
    List<TContract> selectPageList(RowBounds rowBounds, TContract contract);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_contract
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int updateByPrimaryKey(TContract record);
    
    public Long selectPageCount(TContract record);
    List<TContract> selectBidNotice();
    public List<Map> selectConCountByMouth();
    int selectCountByMouth();
    int selectConCount();
}