package com.guochen.dao;

import com.guochen.model.TFile;
import java.util.List;

import org.apache.ibatis.session.RowBounds;

public interface TFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int insert(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    TFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    List<TFile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int updateByPrimaryKey(TFile record);
    
    List<TFile> selectPageList(RowBounds rowBounds, TFile file);
    
    Long selectPageCount(TFile file);
    List<TFile> selectByUseridPageCount(int id);
    
    int deleteByIds(Integer[] ids);
    
    List<TFile> selectByUseridPage(RowBounds rowBounds,int id);
}