package com.guochen.dao;

import com.guochen.model.TMsg;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

public interface TMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int insert(TMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    TMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    List<TMsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_msg
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int updateByPrimaryKey(TMsg record);
    
    public List<TMsg> selectPageList(RowBounds rowBounds, TMsg record);
    public Long selectPageCount(TMsg record);
}