package com.guochen.dao;

import com.guochen.model.TNotice;
import com.guochen.model.TProject;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

public interface TNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int insert(TNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    TNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    List<TNotice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int updateByPrimaryKey(TNotice record);
    
    List<TNotice> selectNoticeBytype(String noticeType);
public List<TNotice> selectPageList(RowBounds rowBounds, TNotice notice);
    public Long selectPageCount(TNotice notice);
    List<TNotice> selectList(TNotice notice);
}