package com.guochen.dao;

import java.util.HashMap;
import com.guochen.model.TProject;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.guochen.model.TProject;

public interface TProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int insert(TProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    TProject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    List<TProject> selectAll();
    List<TProject> selectByDate(String starttime,String endtime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int updateByPrimaryKey(TProject record);
    
    public List<TProject> selectPageList(RowBounds rowBounds, TProject project);
    public List<TProject> selectAccProjectPageList(RowBounds rowBounds, @Param("comId")Integer comId,@Param("proName")String proName);
    
    public Long selectPageCount(TProject project);
    public Long selectAccProjectPageCount(@Param("comId")Integer comId,@Param("proName")String proName);

    public Long selectPageCountToSelectCom(TProject project);
    
    public List<TProject> selectToSelectComPageList(RowBounds rowBounds, TProject project);
    
    public List<TProject> selectToVerfyPageList(RowBounds rowBounds, TProject project);
    //public List<TProject> mselectToVerfyPageList(RowBounds rowBounds, TProject project);
    public Long selectToVerfyPageCount(TProject project);
    public List<TProject> selectToVerfyPageList1(RowBounds rowBounds, TProject project);
    //public List<TProject> mselectToVerfyPageList(RowBounds rowBounds, TProject project);
    public Long selectToVerfyPageCount1(TProject project);
	List<TProject> selectAllOnPage(HashMap map);
    List<TProject> selectlist(@Param("starttime") String starttime,@Param("endtime") String endtime,
    		@Param("proName") String proName,@Param("proStatus") String proStatus);
    List<Map> selectProCountByMouth();
    int selectProCount();
}