package com.guochen.dao;

import com.guochen.model.TRemind;
import java.util.List;

public interface TRemindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remind
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remind
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int insert(TRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remind
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    TRemind selectByPrimaryKey(Integer id);
    List<TRemind> selectNotReadByUserId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remind
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    List<TRemind> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_remind
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int updateByPrimaryKey(TRemind record);
}