package com.guochen.dao;

import com.guochen.model.TRoleAuthority;
import java.util.List;

public interface TRoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_authority
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_authority
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int insert(TRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_authority
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    TRoleAuthority selectByPrimaryKey(Integer id);
    TRoleAuthority selectByRoleAndAuthorityId(TRoleAuthority ra);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_authority
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    List<TRoleAuthority> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_authority
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int updateByPrimaryKey(TRoleAuthority record);
    public int deleteByRoleId(int roleId);
}