package com.guochen.dao;

import com.guochen.model.TProject;
import com.guochen.model.TTemplate;
import java.util.List;

import org.apache.ibatis.session.RowBounds;

public interface TTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int insert(TTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    TTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    List<TTemplate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template
     *
     * @mbg.generated Mon Dec 26 15:46:15 CST 2016
     */
    int updateByPrimaryKey(TTemplate record);
    
    public Long selectPageCount(TTemplate record);
    
    public List<TTemplate> selectPageList(RowBounds rowBounds, TTemplate record);
}